GET http://localhost:3001/

####

GET http://localhost:3001/api/contacts/ HTTP/1.1/

####

GET http://localhost:3001/api/info

####

GET http://localhost:3001/api/contacts/20/ HTTP/1.1/

####

GET http://localhost:3001/api/contacts/2/ HTTP/1.1/

####